# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04def4ab7e03a43a213aadb3a62b48cb652c2ee39c954f7c0a5adc6305b4f30356bb7a30d211f3dad27693b7b331a433e1df2668ba8725df6b9bef2d8a4f732f

test:
  secret_key_base: e8a8e521cb7a44d3acaaa31f26af6417e76a31a9e32d8732974e34df172ddc677518f3919a71f51edd6de1e970ff668d6b8552d0f8d513e067014dd98443d4c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
